name: Pull Request build check

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'keyvalues/**'
      - 'media/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out GameNative
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Inject credentials
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          touch local.properties
          [ -n "${{ secrets.POSTHOG_API_KEY }}" ] && echo "POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }}" >> local.properties
          [ -n "${{ secrets.POSTHOG_HOST }}" ] && echo "POSTHOG_HOST=${{ secrets.POSTHOG_HOST }}" >> local.properties
          [ -n "${{ secrets.SUPABASE_URL }}" ] && echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> local.properties
          [ -n "${{ secrets.SUPABASE_KEY }}" ] && echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> local.properties
          exit 0
      - name: Inject dummy credentials
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          cat <<EOF > local.properties
          POSTHOG_API_KEY=dummy
          POSTHOG_HOST=https://us.i.posthog.com
          SUPABASE_URL=https://dummy.supabase.co
          SUPABASE_KEY=dummy
          EOF
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest
